version: '3.8'

services:
  app:
    container_name: app
    image: node:16-alpine
    ports:
      - "3000:3000"
    volumes:
      - $PWD:/app
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
